#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),{performance}=require('perf_hooks');
const ROOT=path.resolve(__dirname,'..');global.window=global;global.performance=performance;global.CanvasRenderingContext2D=undefined;window.__cdsDebugWarn=()=>{};window.__cdsDebugLog=()=>{};
for(const rel of ['src/scripts/00-polyfills.js','src/scripts/10-data.js','src/scripts/20-core.js','src/scripts/25-data-integrity-v3.js','src/scripts/30-tactics.js','src/scripts/40-match-engine-and-manager-ai.js','src/scripts/45-phases-4-to-7.js','src/scripts/46-phase8-goalkeepers-setpieces.js','src/scripts/47-phase9-manager-ai.js'])vm.runInThisContext(fs.readFileSync(path.join(ROOT,rel),'utf8'),{filename:rel});
const db=buildDB(DATA),forms=Object.keys(FORMATIONS),styles=['balanced','tiki','counter','press','direct','wings','park'],presets=['balanced','possession','counter','highPress','lowBlock','wings'];
const deep=x=>JSON.parse(JSON.stringify(x));
function team(s,form,varIdx,style,preset){const r=autoLineup(s,form,varIdx);return{squad:s,name:s.c,flag:'',color:'#fff',lineup:r.lineup.map(x=>Object.assign({},x,{p:deep(x.p)})),bench:r.bench.map(deep),style,instructions:preset,instructionPreset:preset,axes:Object.assign({},STYLE_AXES[style]||STYLE_AXES.balanced)};}
const rows=[];let invalid=0;
for(let g=0;g<8;g++){
  srand(81000+g*7919);
  const ia=(g*17+19)%db.squads.length,ib=(g*31+53)%db.squads.length;
  const fa=forms[g%forms.length],fb=forms[(g*3+5)%forms.length];
  const va=g%FORMATIONS[fa].variations.length,vb=(g+1)%FORMATIONS[fb].variations.length;
  const sa=styles[g%styles.length],sb=styles[(g+3)%styles.length],pa=presets[g%presets.length],pb=presets[(g+2)%presets.length];
  const sim=new MatchSim(team(db.squads[ia],fa,va,sa,pa),team(db.squads[ib],fb,vb,sb,pb),{labMode:true});
  sim.setTeamInstructions(0,pa);sim.setTeamInstructions(1,pb);sim.setInteractive(g%2);
  let steps=0;while(!sim.isOver()&&steps<500000){sim.step(1/60);steps++;}
  const finite=sim.teams.flatMap(t=>t.players).every(p=>[p.x,p.y,p.stamina,p.rating].every(Number.isFinite))&&Number.isFinite(sim.ball.x)&&Number.isFinite(sim.ball.y);
  if(!finite||!sim.isOver())invalid++;
  const managers=[sim.getManagerData(0),sim.getManagerData(1)];
  for(const d of managers){for(const v of Object.values(d.metrics))if(!Number.isFinite(v)||v<0)throw new Error('métrica de treinador inválida');for(const h of d.history.filter(x=>x.type==='change')){if(!h.action||!h.expected||!h.evidence)throw new Error('decisão sem rastreabilidade');}}
  const ai=sim._aiTeam,aiData=managers[ai];if(aiData.metrics.preMatchPlans!==1)throw new Error('IA sem plano pré-jogo');if(aiData.metrics.substitutions>3)throw new Error('IA excedeu limite próprio de substituições');
  rows.push({game:g+1,seed:81000+g*7919,score:sim.score,steps,finite,ai,manager:aiData,stats:sim.stats.map(s=>({shots:s.shots,onTarget:s.onTarget,xg:s.xg,passes:s.passes,passOk:s.passOk,corners:s.corners,fouls:s.fouls,yellow:s.yellow,red:s.red,setPieceShots:s.setPieceShots,setPieceGoals:s.setPieceGoals,managerAnalyses:s.managerAnalyses,managerDiagnoses:s.managerDiagnoses,managerChanges:s.managerChanges,managerSubstitutions:s.managerSubstitutions,managerEvaluations:s.managerEvaluations,managerSuccessfulChanges:s.managerSuccessfulChanges,managerFailedChanges:s.managerFailedChanges,managerInconclusiveChanges:s.managerInconclusiveChanges,managerReversals:s.managerReversals,managerPreMatchPlans:s.managerPreMatchPlans}))});
}
const sum=fn=>rows.reduce((a,r)=>a+fn(r),0),games=rows.length,total=k=>sum(r=>(r.stats[0][k]||0)+(r.stats[1][k]||0));
const goals=sum(r=>r.score[0]+r.score[1]),shots=total('shots'),passes=total('passes');
const summary={games,engineVersion:CDS_PHASE9.VERSION,fixedStep:1/60,invalidStates:invalid,goalsPerMatch:goals/games,shotsPerMatch:shots/games,xgPerMatch:total('xg')/games,onTargetRate:total('onTarget')/Math.max(1,shots),passCompletion:total('passOk')/Math.max(1,passes),cornersPerMatch:total('corners')/games,foulsPerMatch:total('fouls')/games,setPieceShotsPerMatch:total('setPieceShots')/games,manager:{analyses:total('managerAnalyses'),diagnoses:total('managerDiagnoses'),changes:total('managerChanges'),substitutions:total('managerSubstitutions'),evaluations:total('managerEvaluations'),successful:total('managerSuccessfulChanges'),failed:total('managerFailedChanges'),inconclusive:total('managerInconclusiveChanges'),reversals:total('managerReversals'),preMatchPlans:total('managerPreMatchPlans'),changesPerMatch:total('managerChanges')/games}};
const baselinePath=path.join(ROOT,'reports/phase8/regression8-v510.json');if(fs.existsSync(baselinePath)){const b=JSON.parse(fs.readFileSync(baselinePath,'utf8')).summary,pct=(a,z)=>a?(z-a)/a:0;summary.pairedBaseline={engineVersion:b.engineVersion,goalsPerMatch:b.goalsPerMatch,shotsPerMatch:b.shotsPerMatch,xgPerMatch:b.xgPerMatch,onTargetRate:b.onTargetRate,passCompletion:b.passCompletion,cornersPerMatch:b.cornersPerMatch,foulsPerMatch:b.foulsPerMatch};summary.pairedDelta={goals:pct(b.goalsPerMatch,summary.goalsPerMatch),shots:pct(b.shotsPerMatch,summary.shotsPerMatch),xg:pct(b.xgPerMatch,summary.xgPerMatch),onTarget:summary.onTargetRate-b.onTargetRate,passCompletion:summary.passCompletion-b.passCompletion,corners:pct(b.cornersPerMatch,summary.cornersPerMatch),fouls:pct(b.foulsPerMatch,summary.foulsPerMatch)};}
if(invalid)throw new Error('regressão com estados inválidos: '+invalid);if(summary.manager.preMatchPlans!==games)throw new Error('quantidade de planos pré-jogo inválida');if(summary.manager.analyses<games*5)throw new Error('poucas análises da IA');
const dir=path.join(ROOT,'reports/phase9');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'regression8-v520.json'),JSON.stringify({summary,matches:rows},null,2));
const md=`# Regressão funcional Fase 9 — v5.2.0 (8 partidas)\n\n- Estados inválidos: **${invalid}**\n- Gols/jogo: **${summary.goalsPerMatch.toFixed(3)}**\n- Chutes/jogo: **${summary.shotsPerMatch.toFixed(3)}**\n- xG/jogo: **${summary.xgPerMatch.toFixed(3)}**\n- No alvo: **${(summary.onTargetRate*100).toFixed(1)}%**\n- Passes certos: **${(summary.passCompletion*100).toFixed(1)}%**\n- Escanteios/jogo: **${summary.cornersPerMatch.toFixed(3)}**\n- Faltas/jogo: **${summary.foulsPerMatch.toFixed(3)}**\n- Análises da IA: **${summary.manager.analyses}**\n- Diagnósticos: **${summary.manager.diagnoses}**\n- Mudanças: **${summary.manager.changes}** (${summary.manager.changesPerMatch.toFixed(2)}/jogo)\n- Substituições contextuais: **${summary.manager.substitutions}**\n- Avaliações posteriores: **${summary.manager.evaluations}**\n- Mudanças positivas: **${summary.manager.successful}**\n- Mudanças negativas: **${summary.manager.failed}**\n- Avaliações inconclusivas: **${summary.manager.inconclusive}**\n- Reversões: **${summary.manager.reversals}**\n${summary.pairedDelta?`- Delta pareado vs 5.1.0 — gols: **${(summary.pairedDelta.goals*100).toFixed(1)}%**, chutes: **${(summary.pairedDelta.shots*100).toFixed(1)}%**, xG: **${(summary.pairedDelta.xg*100).toFixed(1)}%**, passes: **${(summary.pairedDelta.passCompletion*100).toFixed(1)} p.p.**\n`:''}`;
fs.writeFileSync(path.join(dir,'regression8-v520.md'),md);console.log(JSON.stringify(summary,null,2));
