#!/usr/bin/env bash
# R18.51 · cadeia completa das candidatas que MEDIRAM efeito.
# Fora: OS-11 (separacao) — medida e nao cumpriu.
set -euo pipefail
BASE="dist/COPA DOS SONHOS - R18.50 - PRESERVAR ENERGIA.html"
OUT="dist/COPA DOS SONHOS - R18.72 - JOGO DE FUTEBOL.html"
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
node tools/r1851/patch_field_name_suffix.js        --in="$BASE"     --out="$T/1.html"
node tools/r1851/patch_os08_oop_role_reconnect.js  --in="$T/1.html" --out="$T/2.html"
node tools/r1851/patch_os10_foul_funnel.js         --in="$T/2.html" --out="$T/3.html"
node tools/r1851/patch_os12_cross_needs_target.js  --in="$T/3.html" --out="$T/4.html"
node tools/r1851/patch_os16_carry.js --limiar=55 --teto=2 --in="$T/4.html" --out="$T/5.html"
node tools/r1851/patch_os14_penalty.js             --in="$T/5.html" --out="$T/6.html"
node tools/r1851/patch_os18_blockable_shots.js     --in="$T/6.html" --out="$T/7.html"
node tools/r1851/patch_os19_gk_angle.js            --in="$T/7.html" --out="$T/8.html"
node tools/r1851/patch_os20_setpiece_hud.js        --in="$T/8.html" --out="$T/9.html"
node tools/r1851/patch_os21_wall_and_taker.js      --in="$T/9.html" --out="$T/10.html"
node tools/r1851/patch_os22_clockrate.js --clockRate=0.16 --in="$T/10.html" --out="$T/11.html"
node tools/r1851/patch_os23_xg_and_corners.js      --in="$T/11.html" --out="$T/12.html"
node tools/r1851/patch_os25_marking_reach.js       --in="$T/12.html" --out="$T/13.html"
node tools/r1851/patch_os26_lane_spread.js         --in="$T/13.html" --out="$T/14.html"
node tools/r1851/patch_os27_cut_inside.js          --in="$T/14.html" --out="$T/15.html"
node tools/r1851/patch_os31_freekick_sense.js      --in="$T/15.html" --out="$T/16.html"
node tools/r1851/patch_os36_freekick_distance.js   --in="$T/16.html" --out="$T/17.html"
node tools/r1851/patch_os37_smooth_corrections.js --vcorr=5 --in="$T/17.html" --out="$T/18.html"
node tools/r1851/patch_os39_block_on_flight.js     --in="$T/18.html" --out="$T/19.html"
# OS-40 REPROVADA (trava de profundidade nao era a causa) — fora da cadeia.
node tools/r1851/patch_os41_threat_range.js        --in="$T/19.html" --out="$T/20.html"
node tools/r1851/patch_os42_contest_the_cross.js   --in="$T/20.html" --out="$T/21.html"
node tools/r1851/patch_os43_aerial_duel.js         --in="$T/21.html" --out="$T/22.html"
node tools/r1851/patch_os44_aerial_duel_distance.js --in="$T/22.html" --out="$T/23.html"
node tools/r1851/patch_os45_cross_accuracy.js      --in="$T/23.html" --out="$T/24.html"
node tools/r1851/patch_os46_anim_wiring.js         --in="$T/24.html" --out="$T/25.html"
node tools/r1851/patch_os47_spin_move.js           --in="$T/25.html" --out="$OUT"
echo "-> $OUT"
